// Central translation file — single source of truth for all UI text
// Usage: import { TEXT } from '@/lib/i18n'
//        const { lang } = useLang()
//        TEXT.dashboard.hero[lang]

export type Lang = 'en' | 'tr'

function t(en: string, tr: string) { return { en, tr } }

export const TEXT = {
  common: {
    connectWallet:  t('Connect your wallet', 'Cüzdanını bağla'),
    loading:        t('Loading...', 'Yükleniyor...'),
    copied:         t('Copied!', 'Kopyalandı!'),
    copyLink:       t('Copy Link', 'Linki Kopyala'),
    share:          t('Share', 'Paylaş'),
    basescan:       t('Basescan ↗', 'Basescan ↗'),
    noData:         t('—', '—'),
    since:          t('since', 'tarihinden beri'),
    onBase:         t('on Base', "Base'de"),
    dayStreak:      t('day streak', 'günlük seri'),
    viewOnBasescan: t('View on Basescan →', 'Basescan\'da Gör →'),
  },
  dashboard: {
    welcome:     t('Welcome to BaseAmp', 'BaseAmp\'a Hoş Geldin'),
    welcomeSub:  t('Connect your wallet to start earning on Base.', 'Base\'te kazanmaya başlamak için cüzdanını bağla.'),
    hero:        t(
      "What matters on Base is not doing many transactions in one day, but spreading activity over time. Sending GM daily helps you stay active.",
      "Base'te değerli olan şey tek günde yüzlerce işlem atmak değil, bunu zamana yaymaktır. GM göndererek her gün aktif kalabilirsin."
    ),
    stats:       t('Stats', 'İstatistikler'),
    totalTx:     t('Total TX', 'Toplam TX'),
    activeDays:  t('Active Days', 'Aktif Gün'),
    builderScore:t('Builder Score', 'Builder Puanı'),
    gmScore:     t('GM Score', 'GM Puanı'),
    referralCta: t(
      "Share your link and earn 10% from transaction fees generated by users you invite.",
      "Linkini paylaşarak davet ettiğin kullanıcıların işlem ücretlerinden %10 komisyon kazanırsın."
    ),
    steps: [
      { n: '1', en_title: 'Send GM',   tr_title: 'GM Gönder',  en_sub: 'Start daily activity',          tr_sub: 'Günlük aktivite başlat',        href: '/gm',      doneKey: 'gm' },
      { n: '2', en_title: 'Swap',      tr_title: 'Swap',       en_sub: 'Use DEXs to generate activity', tr_sub: 'DEX kullanarak aktivite üret',   href: '/swap',    doneKey: 'swap' },
      { n: '3', en_title: 'Earn',      tr_title: 'Kazan',      en_sub: 'Deposit USDC, interact with DeFi', tr_sub: 'USDC yatır, DeFi kullan',    href: '/earn',    doneKey: 'earn' },
      { n: '4', en_title: 'Deploy',    tr_title: 'Deploy',     en_sub: 'Create a contract on Base',     tr_sub: 'Base\'te kontrat oluştur',       href: '/deploy',  doneKey: 'deploy' },
      { n: '5', en_title: 'Invite',    tr_title: 'Davet Et',   en_sub: 'Share your link, earn 10%',     tr_sub: 'Linkini paylaş, %10 kazan',     href: '/referral',doneKey: 'invite' },
    ],
  },
  gm: {
    connectSub:     t('Send daily GM and earn score', 'Günlük GM gönder ve puan kazan'),
    pageInfo:       t(
      'Sending GM looks simple, but it generates a real daily transaction. Consistent activity over time matters more than volume in a single day.',
      'GM göndermek basit görünür ama her gün gerçek bir işlem (TX) yapmanı sağlar. Zamana yayılmış aktivite, tek günde çok işlemden daha değerlidir.'
    ),
    streakLost:     t('Streak lost. Start again', 'Seri bozuldu. Yeniden başla'),
    streakLostSub:  t('Send GM today to begin a new streak', 'Yeni bir seri başlatmak için bugün GM gönder'),
    streakWarning:  t('Send GM today or lose your', 'Bugün GM gönder yoksa'),
    streakDays:     t('-day streak', ' günlük serin gider'),
    activeToday:    t("You're active today", 'Bugün aktifsin'),
    keepGoing:      t('Keep going (+1 per GM)', 'Devam et (+1 her GM\'de)'),
    sendBtn:        t('Send GM — earn +5 score', 'GM Gönder — +5 puan kazan'),
    sendAgainBtn:   t('Send another GM (+1 score)', 'Tekrar GM Gönder (+1 puan)'),
    sendingBtn:     t('Sending...', 'Gönderiliyor...'),
    urgentBtn:      t('Send GM now — streak at risk!', 'Hemen GM Gönder — serin tehlikede!'),
    hintFirst:      t('Unlimited GM — only your first counts for streak', 'Sınırsız GM — sadece ilki seri için sayılır'),
    hintAgain:      t("You're active today — keep going (+1 per GM)", 'Bugün aktifsin — devam et (+1 her GM\'de)'),
    totalGms:       t('Total GMs', 'Toplam GM'),
    yourRank:       t('Your Rank', 'Sıran'),
    resetsIn:       t('Resets in', 'Sıfırlanıyor'),
    leaderboard:    t('Leaderboard', 'Liderlik Tablosu'),
    noScores:       t('No scores yet — be first!', 'Henüz puan yok — ilk sen ol!'),
    recentGMs:      t('Recent GMs', 'Son GM\'ler'),
    milestones:     t('Milestones', 'Kilometre Taşları'),
    daysToDay:      t('days to Day', 'gün kaldı: Gün'),
    dayToDay:       t('day to Day', 'gün kaldı: Gün'),
    bonusLabel:     t('bonus', 'bonus'),
    gmSent:         t('GM sent', 'GM gönderildi'),
    milestone:      t('milestone!', 'kilometre taşı!'),
    dailyStreak:    t('day streak', 'günlük seri'),
  },
  earn: {
    connectSub: t('Deposit into vaults to earn yield', 'Getiri kazanmak için vault\'lara yatır'),
    pageInfo:   t(
      "Idle tokens can work for you here. Starting small and staying consistent shows more genuine usage than one-time activity.",
      "Boş duran token'ları burada değerlendirebilirsin. Küçük başlayıp zamanla devam etmek daha doğal kullanım gösterir."
    ),
    bestApy:    t('Best APY', 'En İyi APY'),
    totalTvl:   t('Total TVL', 'Toplam TVL'),
    protocols:  t('Protocols', 'Protokoller'),
    all:        t('All', 'Tümü'),
    filter:     t('Filter', 'Filtrele'),
    openVault:  t('Open vault ↗', 'Vault\'u aç ↗'),
    tvl:        t('TVL', 'TVL'),
    apy:        t('APY', 'APY'),
  },
  swap: {
    connectSub:   t('Swap tokens on Base', 'Base\'te token takas et'),
    pageInfo:     t(
      "Swapping tokens is active network usage. Trying different platforms creates a stronger signal than using only one.",
      "Token takası yaparak ağı aktif kullanırsın. Farklı platformları denemek gerçek kullanım sinyali oluşturur."
    ),
    bannerTitle:  t('Best Base DEXs & Aggregators', 'En İyi Base DEX\'ler ve Toplayıcılar'),
    bannerSub:    t('Click any platform to trade directly on Base.', 'Base\'te doğrudan işlem yapmak için herhangi bir platforma tıkla.'),
    aggregators:  t('Aggregators', 'Toplayıcılar'),
    aggregatorDesc: t(
      'Scan multiple DEXs and give you the best price automatically — best for beginners.',
      'Birden fazla DEX\'i tarayıp en iyi fiyatı otomatik bulur — yeni başlayanlar için en kolay seçenek.'
    ),
    dex:          t('DEX', 'DEX'),
    dexDesc:      t(
      'Decentralized exchanges where trades happen directly via liquidity pools.',
      'Likidite havuzları üzerinden direkt işlem yapılan merkeziyetsiz borsalar.'
    ),
    stable:       t('Stablecoin', 'Stablecoin'),
    stableDesc:   t(
      'Optimized for stable-to-stable swaps with minimal slippage.',
      'Minimum kayıpla stablecoin takası için optimize edilmiş.'
    ),
    platforms:    t('platforms', 'platform'),
  },
  deploy: {
    connectSub:   t('Deploy contracts on Base mainnet', 'Base mainnet\'e kontrat deploy et'),
    pageInfo:     t(
      "Even a simple contract deploy counts as real on-chain usage. Fill in the details and deploy directly on Base.",
      "Basit bir kontrat deploy etmek bile ağ üzerinde gerçek kullanım olarak görülür. Bilgileri doldurup Base üzerinde yayınlarsın."
    ),
    contractType: t('Contract Type', 'Kontrat Tipi'),
    parameters:   t('Parameters', 'Parametreler'),
    noParams:     t('No parameters needed — ready to deploy.', 'Parametre gerekmez — deploy\'a hazır.'),
    network:      t('Network: Base Mainnet', 'Ağ: Base Mainnet'),
    builderCode:  t('Builder Code:', 'Builder Kodu:'),
    refDiscount:  t('Referral discount applied', 'Referral indirimi uygulandı'),
    preparing:    t('Preparing deployment...', 'Deploy hazırlanıyor...'),
    deploying:    t('Deploying to Base...', 'Base\'e deploy ediliyor...'),
    deployBtn:    (name: string) => ({ en: `Deploy ${name}`, tr: `${name} Deploy Et` }),
    preparingBtn: t('Preparing...', 'Hazırlanıyor...'),
    deployingBtn: t('Deploying...', 'Deploy ediliyor...'),
    success:      t('deployed successfully', 'başarıyla deploy edildi'),
  },
  referral: {
    connectSub:     t('Get your referral link and start earning', 'Referral linkini al ve kazanmaya başla'),
    referrals:      t('Referrals', 'Referanslar'),
    earned:         t('Earned (ETH)', 'Kazanılan (ETH)'),
    todayScore:     t('Today Score', 'Bugün Puan'),
    commission:     t('Commission', 'Komisyon'),
    commissionVal:  t('10%', '%10'),
    yourLink:       t('Your Referral Link', 'Referral Linkin'),
    copy:           t('Copy', 'Kopyala'),
    share:          t('Share', 'Paylaş'),
    yourReferrals:  t('Your Referrals', 'Referansların'),
    noReferrals:    t('No referrals yet', 'Henüz referans yok'),
    noReferralsSub: t('Share your link to get started', 'Başlamak için linkini paylaş'),
    shareText:      (link: string) => `Join me on BaseAmp!\n\nSend daily GM & earn score\n10% fee discount with my code\n\n${link}`,
  },
}

export function tx(obj: { en: string; tr: string }, lang: Lang): string {
  return obj[lang] ?? obj.en
}
